aziontech/lib

packages/sql/README.MD, packages/sql/src/index.test.ts, packages/sql/src/index.ts, packages/sql/src/types.ts
Add `listTables` method to `azion/sql`.
Example:
By method:
```js
import { listTables } from 'azion/sql';
const result = await listTables('my-db', { debug: true });
```
By client:
```js
import { createClient } from 'azion/sql';
const client = createClient();
const database = await client.getDatabase('my-new-db');
const dbTables = await database.listTables();
const result = dbTables.toObject();
```
Example response:
```json
{
"state": "executed",
"data": [
{
"statement": "PRAGMA",
"rows": [
{
"schema": "main",
"name": "users",
"type": "table",
"ncol": 2,
"wr": 0,
"strict": 0
}
]
}
]
}
```
=> feat: add listTables method to sql package

README.md, packages/client/README.MD, packages/client/src/types.ts, packages/purge/README.md, packages/purge/src/index.test.ts, packages/purge/src/index.ts, packages/purge/src/services/api/index.ts, packages/purge/src/services/api/types.ts, packages/purge/src/types.ts, packages/sql/README.MD, packages/sql/src/index.test.ts, packages/sql/src/index.ts, packages/sql/src/services/api/index.ts, packages/sql/src/services/api/types.ts, packages/sql/src/services/index.ts, packages/sql/src/services/runtime/index.ts, packages/sql/src/types.ts, packages/sql/src/utils/mappers/to-object.ts, packages/storage/README.md, packages/storage/src/index.test.ts, packages/storage/src/index.ts, packages/storage/src/services/api/index.ts, packages/storage/src/services/api/types.d.ts, packages/storage/src/services/runtime/index.ts, packages/storage/src/types.ts, packages/storage/src/utils/index.ts
Updated the return of the azion/storage, azion/sql and azion/purge functions to the standard { data, error }.
Example:
```js
import { createBucket } from 'azion/storage';
const { data, error } = await createBucket({ name: 'my-new-bucket', edge_access: 'read_write' });
if (data) {
console.log(`Bucket created with name: ${data.name}`);
} else {
console.error('Failed to create bucket', error);
}
```
=> feat: updating function returns

packages/client/src/index.ts, packages/config/src/index.ts, packages/config/src/processConfig/helpers/behaviors.ts, packages/config/src/processConfig/index.test.ts, packages/config/src/processConfig/index.ts, packages/config/src/processConfig/strategy/implementations/buildProcessConfigStrategy.ts, packages/config/src/processConfig/strategy/implementations/cacheProcessConfigStrategy.ts, packages/config/src/processConfig/strategy/implementations/domainProcessConfigStrategy.ts, packages/config/src/processConfig/strategy/implementations/originProcessConfigStrategy.ts, packages/config/src/processConfig/strategy/implementations/purgeProcessConfigStrategy.ts, packages/config/src/processConfig/strategy/implementations/rulesProcessConfigStrategy.ts, packages/config/src/processConfig/strategy/processConfigContext.ts, packages/config/src/processConfig/strategy/processConfigStrategy.ts
This function allows for converting a JSON configuration object to an `AzionConfig` object.
Usage:
```js
import { convertJsonConfigToObject } from 'azion';
const config = `{
"origin": [
{
"name": 'my single origin',
"origin_type": 'single_origin',
"addresses": [
{
"address": 'http.bin.org',
},
],
"origin_path": '',
"method": 'ip_hash',
"origin_protocol_policy": 'preserve',
"host_header": '${host}',
"is_origin_redirection_enabled": true,
"connection_timeout": 60,
"timeout_between_bytes": 120,
"hmac_authentication": true,
"hmac_region_name": 'us-east-1',
"hmac_access_key": 'myaccesskey',
"hmac_secret_key": 'secretKey',
},
],
}`;
const configObject = convertJsonConfigToObject(config);
```
Expect:
```js
configObject = {
name: 'my single origin',
type: 'single_origin',
path: '',
addresses: [
{ …
```
=> feat: add convert json config to config object

packages/client/src/index.ts, packages/config/src/processConfig/strategy/implementations/cacheProcessConfigStrategy.ts
`TypeError: The argument to 'typed' at index 1 is not a function (typed), nor an object with signatures as keys and functions as values.
data: {
index: 1,
argument: {
number: [Function],
'Complex | BigNumber | Fraction | Unit': [Function: Complex | BigNumber | Fraction | Unit],
bigint: [Function: bigint],
'Matrix | Matrix': [Object] }`
1 - Create an isolated instance of mathjs that has its own scope and does not interfere with the global environment, keeping its configurations encapsulated.
=> fix: resolve mathjs runtime configuration conflict

packages/config/src/constants.ts, packages/config/src/processConfig/helpers/schema.ts, packages/config/src/processConfig/helpers/schemaManifest.ts, packages/config/src/processConfig/index.test.ts, packages/config/src/processConfig/index.ts, packages/config/src/processConfig/strategy/implementations/secure/networkListProcessConfigStrategy.ts
This pull request introduces a new feature to handle network lists in the configuration processing system. The changes include adding constants, modifying schemas, updating validation logic, and adding new tests to ensure the correct processing of network lists.
* [`packages/config/src/constants.ts`](diffhunk://#diff-211627e272d8e1db6e01d86ea127b286632a3fb2bccbbe4e29844d4b72ef9c38R88-R89): Added `NETWORK_LIST_TYPES` constant to define the accepted values for network lists.
* [`packages/config/src/processConfig/helpers/schema.ts`](diffhunk://#diff-d7f5cddc4e51d20a98665915e59cb0d9b527b0e01e56d2dc02496173edf7602cR6): Updated the schema to use `NETWORK_LIST_TYPES` for the `listType` field. [[1]](diffhunk://#diff-d7f5cddc4e51d20a98665915e59cb0d9b527b0e01e56d2dc02496173edf7602cR6) …
=> feat: add network list types and implement processing strategy

packages/config/README.md
This pull request updates the `packages/config/README.md` file to include new documentation and examples for handling network lists and converting JSON configurations to objects. The most important changes include adding new sections and examples, updating the type definitions, and modifying the existing configuration examples.
=> docs: add example convertJsonConfigToObject and update README

packages/config/src/types.ts
This pull request introduces new configurations for the Web Application Firewall (WAF) in the `packages/config/src/types.ts` file. The changes include adding new types and properties to support the WAF configuration.
* Added `WafMode` and `WafSensitivity` to the import statements.
* Introduced a new `waf` property in the `AzionConfig` type to hold WAF configurations.
* Defined a new `AzionWaf` type with various properties for configuring different WAF rules and their sensitivities.
=> feat: add WAF configuration type and properties to AzionConfig

packages/config/src/constants.ts, packages/config/src/processConfig/helpers/schemaManifest.ts, packages/config/src/processConfig/index.test.ts
Created a new schema manifest to handle configuration validation for the `convertJsonConfigToObject` function. This schema is designed to validate the structure of configurations, ensuring data integrity and proper formatting.
- Created `schemaManifest.ts` with comprehensive validation schemas for:
- Application schema
- Domains schema
- Firewall Schema
- Added validation for required fields and proper data types
- Implemented enum validations for specific fields
- Added clear error messages for validation failures
- Maintained consistency with existing schema structure
- Ensured proper typing and TypeScript support
This change is necessary to:
1. Validate processed configurations before they are converted back to config objects
2. Ensure data integrity during the conversion process
3. …
=> feat:  firewall, domains and applications manifest schema

README.md, packages/config/README.md
This pull request adds support for Web Application Firewall (WAF) configurations to the project. The changes include updates to the configuration object and documentation to integrate WAF settings.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R204-R205): Added  `waf` properties to the configuration object. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R204-R205) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R223-R224)
* [`packages/config/README.md`](diffhunk://#diff-08bfd3800f046f2c979ef3bdc4c668abb136c724eb8de752af1ad2fd732840ccR28): Added `AzionWaf` to the list of configuration options and detailed the properties of the WAF configuration. …
=> docs: add WAF documentation

package-lock.json, package.json
This pull request includes a small change to the `package.json` file. The change adds the `crypto-browserify` dependency to the project.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R213): Added `crypto-browserify` dependency with version `^3.12.1`.
=> fix: add crypto-browserify as a dependency

package-lock.json, package.json
This pull request includes a small change to the `package.json` file. The change adds a new entry for the `unenv-preset/src/polyfills` directory to map to the corresponding source files in the `packages/unenv-preset` directory.
=> fix: export polyfills path for unenv-preset package

packages/unenv-preset/src/index.ts, packages/unenv-preset/src/polyfills/node/globals/navigator.js, packages/unenv-preset/src/polyfills/node/globals/performance.js
This pull request adds temporary polyfills for `performance` and `navigator` in the `unenv-preset` package. These changes ensure compatibility with environments that do not natively support these global objects.
* [`packages/unenv-preset/src/index.ts`](diffhunk://#diff-40a0c89863390a48518ad7870d9042ad049b987f88f48b67368e0b4f9570a450R17-R18): Added `performance` and `navigator` to the list of polyfills.
* [`packages/unenv-preset/src/polyfills/node/globals/navigator.js`](diffhunk://#diff-6b23060d8dbbbd734331cd081aacf728e59d0e556981b6fe2e2d4f9acf6f9292R1-R6): Introduced a temporary polyfill for `navigator` with a basic `userAgent` property.
* [`packages/unenv-preset/src/polyfills/node/globals/performance.js`](diffhunk://#diff-91bcc7dd4e74c11205ccdc264143a10035d658d4621fd5237b1fa1c1a1d095f5R1- …
=> feat: add temporary polyfills for performance and navigator in unenv-preset

packages/config/src/configProcessor/helpers/schemaManifest.ts, packages/config/src/configProcessor/processStrategy/implementations/domainProcessConfigStrategy.ts, packages/config/src/configProcessor/processStrategy/implementations/secure/firewallProcessConfigStrategy.test.ts, packages/config/src/configProcessor/processStrategy/implementations/secure/firewallProcessConfigStrategy.ts
This pull request includes several changes aimed at improving the configuration processing and testing for firewall and domain configurations. The most important changes include updates to the schema manifest, adjustments in the domain and firewall processing strategies, and modifications to the test cases.
* [`packages/config/src/configProcessor/helpers/schemaManifest.ts`](diffhunk://#diff-9a4bca5c0ce3364aea1bda2adeebd9bb4b269b1379b53d3f7bfe021d31bd695cL478-R480): Simplified the `firewall` schema by spreading `schemaFirewallManifest` and updated error messages for additional properties. [[1]](diffhunk://#diff-9a4bca5c0ce3364aea1bda2adeebd9bb4b269b1379b53d3f7bfe021d31bd695cL478-R480) [[2]](diffhunk://#diff-9a4bca5c0ce3364aea1bda2adeebd9bb4b269b1379b53d3f7bfe021d31bd695cL800-R798)
* …
=> fix: adjustments in the domain and firewall processing transform config

packages/presets/src/presets/next/static/prebuild.js
This PR fixes an issue with Next.js 14.2+ static exports where the build process would fail when trying to copy files referenced in the app-path-routes-manifest that don't physically exist (like _not-found.html).
The fix properly handles missing files by:
1. Adding error handling for ENOENT errors during file copy operations
2. Improving async flow with Promise.all to ensure all operations complete properly
=> fix(nextjs-preset): handle missing files in app-path-routes-manifest

packages/bundler/src/helpers/azion-local-polyfills.ts, packages/bundler/src/polyfills/azion/storage/storage.polyfills.js
This pull request introduces changes to enhance Azion-related polyfills by adding support for the `Azion.Storage` global object. The changes ensure that `Azion.Storage` is properly initialized and linked to the corresponding polyfill.
* [`packages/bundler/src/helpers/azion-local-polyfills.ts`](diffhunk://#diff-a534d27256a11d79145f29a7a133a8445b64f7430ef15654acc5a547a620a807R16): Added a mapping for `Azion.Storage` to the `storage.polyfills.js` file, ensuring the polyfill is included in the bundler.
* [`packages/bundler/src/polyfills/azion/storage/storage.polyfills.js`](diffhunk://#diff-46dc1fbd1c625240135d0f56b0838bc09672f625b2b86d76a58f15a293598f1bR200-R202): Initialized `globalThis.Azion.Storage` with the `Storage` class, ensuring the `Azion.Storage` global object is available and …
=> fix: add Azion.Storage to globalThis for polyfill

packages/bundler/src/polyfills/promises/index.js, packages/unenv-preset/src/index.ts, packages/unenv-preset/src/polyfills/node/https.js, packages/unenv-preset/src/polyfills/node/internal/_internal.js, packages/unenv-preset/src/polyfills/node/internal/util/inherits.js, packages/unenv-preset/src/polyfills/node/internal/util/legacy-types.js, packages/unenv-preset/src/polyfills/node/internal/util/log.js, packages/unenv-preset/src/polyfills/node/internal/util/mime.js, packages/unenv-preset/src/polyfills/node/internal/util/promisify.js, packages/unenv-preset/src/polyfills/node/internal/util/types.js, packages/unenv-preset/src/polyfills/node/util.js
This pull request introduces significant updates to the `unenv-preset` package, focusing on enhancing Node.js polyfills and improving the `https` request implementation. It also includes some minor code simplifications and reorganization. Below is a categorized summary of the most important changes:
* Added a comprehensive set of utility functions and classes in `internal/util` to mimic Node.js behavior, including `inherits`, `MIMEType`, `MIMEParams`, `promisify`, and various type-checking utilities like `isRegExp` and `isDate`. These updates improve compatibility with Node.js APIs. [[1]](diffhunk://#diff-a80b3a3840b7fe8f11677d198b841d1ce438f3dfd116131aaeff1003d41046a4R1-R15) [[2]](diffhunk://#diff-9ada7be1bf71d6560d64a4488c3ea07932e6ba358374ab4a9917a4f457b1cdacR1-R45) …
=> fix: polyfills for Node.js compatibility

packages/unenv-preset/src/index.ts, packages/unenv-preset/src/polyfills/node/globals/clear-interval.js
This pull request introduces updates to the `unenv-preset` package, including the addition of a polyfill for `clearInterval` and the removal of an unused utility alias. These changes enhance compatibility and simplify the codebase.
* **Added `clearInterval` polyfill**: Introduced a new polyfill for `clearInterval` in `packages/unenv-preset/src/polyfills/node/globals/clear-interval.js`. This implementation ensures compatibility with various interval object formats by checking for properties like `id`, `_id`, or a `close` method.
* **Registered `clearInterval` in exports**: Added the `clearInterval` polyfill to the `globals` section in `packages/unenv-preset/src/index.ts`.
* **Removed unused alias for `util/types`**: Eliminated the alias for `util/types` in …
=> fix: add polyfill for clearInterval and update injection in unenv preset

packages/config/src/types.ts, packages/presets/src/index.ts, packages/presets/src/presets/opennextjs/config.ts, packages/presets/src/presets/opennextjs/index.ts, packages/presets/src/presets/opennextjs/metadata.ts, packages/presets/src/presets/opennextjs/prebuild.ts
This pull request introduces a new preset, `opennextjs`, to the `packages/presets` module and adds support for skipping project builds in the build context. The changes include defining the configuration, metadata, and prebuild logic for the new preset, as well as updating the build context interface to accommodate the new feature.
* Added a new preset, `opennextjs`, with its configuration, metadata, and prebuild logic. This includes defining the build rules, origin settings, and edge function behaviors in `opennextjs/config.ts` (`packages/presets/src/presets/opennextjs/config.ts`).
* Created `opennextjs/metadata.ts` to define metadata for the preset, including its name (`packages/presets/src/presets/opennextjs/metadata.ts`).
* Implemented `opennextjs/prebuild.ts` to handle prebuild …
=> feat: add OpenNextjs preset

packages/bundler/src/polyfills/azion/fetch/context/fetch.context.js, packages/config/src/configProcessor/processStrategy/implementations/application/edgeApplicationProcessConfigStrategy.ts, packages/presets/src/presets/angular/config.ts, packages/presets/src/presets/angular/prebuild.ts, packages/presets/src/presets/javascript/config.ts
This pull request introduces several significant updates to the Angular and JavaScript presets, as well as improvements to configuration defaults and the Azion fetch context. The main changes focus on updating build output directories, enhancing configuration with workloads and function instances, and adjusting default behaviors for edge functions.
**Preset and Build Process Updates:**
* Changed the Angular preset's build output directory from `.edge/storage` to `./dist`, updating both the configuration and the prebuild script to reflect this change. This includes moving browser files to the new `dist` directory. [[1]](diffhunk://#diff-0b08b39abf37c25eb06b6ad389c4c159dda7a8f9d6b56c34983fe57f0abbba1fL11-R11) [[2]](diffhunk://#diff-347b372a2e640f0f0b3797c1bf24b73c278111a83930bb58e7bbffcaf48c …
=> fix: update storage paths and enable edge functions by default across presets

packages/bundler/src/polyfills/azion/fetch/context/fetch.context.js, packages/config/src/configProcessor/helpers/azion.config.example.ts, packages/config/src/configProcessor/helpers/schema.ts, packages/config/src/configProcessor/processStrategy/implementations/storageProcessConfigStrategy.ts, packages/config/src/types.ts, packages/presets/src/presets/angular/config.ts, packages/presets/src/presets/astro/config.ts, packages/presets/src/presets/docusaurus/config.ts, packages/presets/src/presets/eleventy/config.ts, packages/presets/src/presets/gatsby/config.ts, packages/presets/src/presets/hexo/config.ts, packages/presets/src/presets/html/config.ts, packages/presets/src/presets/hugo/config.ts, packages/presets/src/presets/jekyll/config.ts, packages/presets/src/presets/next/config.ts, packages/presets/src/presets/nuxt/config.ts, packages/presets/src/presets/opennextjs/config.ts, packages/presets/src/presets/preact/config.ts, packages/presets/src/presets/qwik/config.ts, packages/presets/src/presets/react/config.ts, packages/presets/src/presets/stencil/config.ts, packages/presets/src/presets/svelte/config.ts, packages/presets/src/presets/vitepress/config.ts, packages/presets/src/presets/vue/config.ts, packages/presets/src/presets/vuepress/config.ts
This pull request introduces support for a required storage bucket prefix across the configuration system, presets, and fetch context logic. The main focus is to ensure that every storage bucket configuration includes a `prefix` property, and that this prefix is properly handled throughout the codebase, including when accessing files and generating preset configs.
**Configuration schema and type updates:**
- Made the `prefix` property required for all storage bucket configurations in the schema (`schema.ts`), and updated error messages accordingly. (`[packages/config/src/configProcessor/helpers/schema.tsR455-R460](diffhunk://#diff-3badacac288aefceb8f0de08abfc2b00288c97ea70859fe424844b7b7096f720R455-R460)`)
- Updated the `AzionBucket` type to include a required `prefix` field. …
=> fix: add storage prefix support across all presets and configurations

packages/config/src/configProcessor/processStrategy/implementations/application/edgeApplicationProcessConfigStrategy.ts, packages/presets/src/presets/opennextjs/config.ts
This pull request introduces two key configuration changes aimed at enabling more features by default and expanding access permissions for asset storage. These updates impact both application process configuration and asset storage presets.
Configuration changes:
* Updated the `application_accelerator` feature in `edgeApplicationProcessConfigStrategy.ts` to be enabled by default unless explicitly disabled, by changing the fallback value to `true`.
* Changed the `edgeAccess` permission for asset storage in the OpenNext.js preset configuration from `'read_only'` to `'read_write'`, allowing both read and write operations on assets at the edge.
=> fix: adjustments to generate manifest and presets

packages/config/src/configProcessor/processStrategy/implementations/secure/networkListProcessConfigStrategy.test.ts, packages/config/src/configProcessor/processStrategy/implementations/secure/wafProcessConfigStrategy.test.ts
Add tests for following secure process config strategies:
- WAF
- NetworkList
=> test: add process config strategies tests for secure
